name: Node.js CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.7.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.7.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Push to main if tests passed
        if: success()
        uses: ad-m/github-push-action@master
        with:
          branch: main