# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.7.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'
          cache: 'npm'
      - run: npm install
      
      - if: success()
      uses: ad-m/github-push-action@master
      with:
        branch: main
